// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/grpcbin/grpcbin.proto

package grpcbin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyMessage_Enum int32

const (
	DummyMessage_ENUM_0 DummyMessage_Enum = 0
	DummyMessage_ENUM_1 DummyMessage_Enum = 1
	DummyMessage_ENUM_2 DummyMessage_Enum = 2
)

// Enum value maps for DummyMessage_Enum.
var (
	DummyMessage_Enum_name = map[int32]string{
		0: "ENUM_0",
		1: "ENUM_1",
		2: "ENUM_2",
	}
	DummyMessage_Enum_value = map[string]int32{
		"ENUM_0": 0,
		"ENUM_1": 1,
		"ENUM_2": 2,
	}
)

func (x DummyMessage_Enum) Enum() *DummyMessage_Enum {
	p := new(DummyMessage_Enum)
	*p = x
	return p
}

func (x DummyMessage_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DummyMessage_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_grpcbin_grpcbin_proto_enumTypes[0].Descriptor()
}

func (DummyMessage_Enum) Type() protoreflect.EnumType {
	return &file_proto_grpcbin_grpcbin_proto_enumTypes[0]
}

func (x DummyMessage_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DummyMessage_Enum.Descriptor instead.
func (DummyMessage_Enum) EnumDescriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{3, 0}
}

type HeadersMessage struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Metadata      map[string]*HeadersMessage_Values `protobuf:"bytes,1,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersMessage) Reset() {
	*x = HeadersMessage{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersMessage) ProtoMessage() {}

func (x *HeadersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersMessage.ProtoReflect.Descriptor instead.
func (*HeadersMessage) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{0}
}

func (x *HeadersMessage) GetMetadata() map[string]*HeadersMessage_Values {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SpecificErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecificErrorRequest) Reset() {
	*x = SpecificErrorRequest{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificErrorRequest) ProtoMessage() {}

func (x *SpecificErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificErrorRequest.ProtoReflect.Descriptor instead.
func (*SpecificErrorRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{1}
}

func (x *SpecificErrorRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SpecificErrorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{2}
}

type DummyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FString       string                 `protobuf:"bytes,1,opt,name=f_string,json=fString,proto3" json:"f_string,omitempty"`
	FStrings      []string               `protobuf:"bytes,2,rep,name=f_strings,json=fStrings,proto3" json:"f_strings,omitempty"`
	FInt32        int32                  `protobuf:"varint,3,opt,name=f_int32,json=fInt32,proto3" json:"f_int32,omitempty"`
	FInt32S       []int32                `protobuf:"varint,4,rep,packed,name=f_int32s,json=fInt32s,proto3" json:"f_int32s,omitempty"`
	FEnum         DummyMessage_Enum      `protobuf:"varint,5,opt,name=f_enum,json=fEnum,proto3,enum=grpcbin.DummyMessage_Enum" json:"f_enum,omitempty"`
	FEnums        []DummyMessage_Enum    `protobuf:"varint,6,rep,packed,name=f_enums,json=fEnums,proto3,enum=grpcbin.DummyMessage_Enum" json:"f_enums,omitempty"`
	FSub          *DummyMessage_Sub      `protobuf:"bytes,7,opt,name=f_sub,json=fSub,proto3" json:"f_sub,omitempty"`
	FSubs         []*DummyMessage_Sub    `protobuf:"bytes,8,rep,name=f_subs,json=fSubs,proto3" json:"f_subs,omitempty"`
	FBool         bool                   `protobuf:"varint,9,opt,name=f_bool,json=fBool,proto3" json:"f_bool,omitempty"`
	FBools        []bool                 `protobuf:"varint,10,rep,packed,name=f_bools,json=fBools,proto3" json:"f_bools,omitempty"`
	FInt64        int64                  `protobuf:"varint,11,opt,name=f_int64,json=fInt64,proto3" json:"f_int64,omitempty"`
	FInt64S       []int64                `protobuf:"varint,12,rep,packed,name=f_int64s,json=fInt64s,proto3" json:"f_int64s,omitempty"`
	FBytes        []byte                 `protobuf:"bytes,13,opt,name=f_bytes,json=fBytes,proto3" json:"f_bytes,omitempty"`
	FBytess       [][]byte               `protobuf:"bytes,14,rep,name=f_bytess,json=fBytess,proto3" json:"f_bytess,omitempty"`
	FFloat        float32                `protobuf:"fixed32,15,opt,name=f_float,json=fFloat,proto3" json:"f_float,omitempty"`
	FFloats       []float32              `protobuf:"fixed32,16,rep,packed,name=f_floats,json=fFloats,proto3" json:"f_floats,omitempty"` // TODO: timestamp, duration, oneof, any, maps, fieldmask, wrapper type, struct, listvalue, value, nullvalue, deprecated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyMessage) Reset() {
	*x = DummyMessage{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyMessage) ProtoMessage() {}

func (x *DummyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyMessage.ProtoReflect.Descriptor instead.
func (*DummyMessage) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{3}
}

func (x *DummyMessage) GetFString() string {
	if x != nil {
		return x.FString
	}
	return ""
}

func (x *DummyMessage) GetFStrings() []string {
	if x != nil {
		return x.FStrings
	}
	return nil
}

func (x *DummyMessage) GetFInt32() int32 {
	if x != nil {
		return x.FInt32
	}
	return 0
}

func (x *DummyMessage) GetFInt32S() []int32 {
	if x != nil {
		return x.FInt32S
	}
	return nil
}

func (x *DummyMessage) GetFEnum() DummyMessage_Enum {
	if x != nil {
		return x.FEnum
	}
	return DummyMessage_ENUM_0
}

func (x *DummyMessage) GetFEnums() []DummyMessage_Enum {
	if x != nil {
		return x.FEnums
	}
	return nil
}

func (x *DummyMessage) GetFSub() *DummyMessage_Sub {
	if x != nil {
		return x.FSub
	}
	return nil
}

func (x *DummyMessage) GetFSubs() []*DummyMessage_Sub {
	if x != nil {
		return x.FSubs
	}
	return nil
}

func (x *DummyMessage) GetFBool() bool {
	if x != nil {
		return x.FBool
	}
	return false
}

func (x *DummyMessage) GetFBools() []bool {
	if x != nil {
		return x.FBools
	}
	return nil
}

func (x *DummyMessage) GetFInt64() int64 {
	if x != nil {
		return x.FInt64
	}
	return 0
}

func (x *DummyMessage) GetFInt64S() []int64 {
	if x != nil {
		return x.FInt64S
	}
	return nil
}

func (x *DummyMessage) GetFBytes() []byte {
	if x != nil {
		return x.FBytes
	}
	return nil
}

func (x *DummyMessage) GetFBytess() [][]byte {
	if x != nil {
		return x.FBytess
	}
	return nil
}

func (x *DummyMessage) GetFFloat() float32 {
	if x != nil {
		return x.FFloat
	}
	return 0
}

func (x *DummyMessage) GetFFloats() []float32 {
	if x != nil {
		return x.FFloats
	}
	return nil
}

type IndexReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Endpoints     []*IndexReply_Endpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexReply) Reset() {
	*x = IndexReply{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexReply) ProtoMessage() {}

func (x *IndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexReply.ProtoReflect.Descriptor instead.
func (*IndexReply) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{4}
}

func (x *IndexReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IndexReply) GetEndpoints() []*IndexReply_Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type HeadersMessage_Values struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersMessage_Values) Reset() {
	*x = HeadersMessage_Values{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersMessage_Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersMessage_Values) ProtoMessage() {}

func (x *HeadersMessage_Values) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersMessage_Values.ProtoReflect.Descriptor instead.
func (*HeadersMessage_Values) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HeadersMessage_Values) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type DummyMessage_Sub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FString       string                 `protobuf:"bytes,1,opt,name=f_string,json=fString,proto3" json:"f_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyMessage_Sub) Reset() {
	*x = DummyMessage_Sub{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyMessage_Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyMessage_Sub) ProtoMessage() {}

func (x *DummyMessage_Sub) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyMessage_Sub.ProtoReflect.Descriptor instead.
func (*DummyMessage_Sub) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DummyMessage_Sub) GetFString() string {
	if x != nil {
		return x.FString
	}
	return ""
}

type IndexReply_Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexReply_Endpoint) Reset() {
	*x = IndexReply_Endpoint{}
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexReply_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexReply_Endpoint) ProtoMessage() {}

func (x *IndexReply_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcbin_grpcbin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexReply_Endpoint.ProtoReflect.Descriptor instead.
func (*IndexReply_Endpoint) Descriptor() ([]byte, []int) {
	return file_proto_grpcbin_grpcbin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *IndexReply_Endpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexReply_Endpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_grpcbin_grpcbin_proto protoreflect.FileDescriptor

const file_proto_grpcbin_grpcbin_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/grpcbin/grpcbin.proto\x12\agrpcbin\"\xd2\x01\n" +
	"\x0eHeadersMessage\x12A\n" +
	"\bMetadata\x18\x01 \x03(\v2%.grpcbin.HeadersMessage.MetadataEntryR\bMetadata\x1a \n" +
	"\x06Values\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1a[\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.grpcbin.HeadersMessage.ValuesR\x05value:\x028\x01\"B\n" +
	"\x14SpecificErrorRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0e\n" +
	"\fEmptyMessage\"\xde\x04\n" +
	"\fDummyMessage\x12\x19\n" +
	"\bf_string\x18\x01 \x01(\tR\afString\x12\x1b\n" +
	"\tf_strings\x18\x02 \x03(\tR\bfStrings\x12\x17\n" +
	"\af_int32\x18\x03 \x01(\x05R\x06fInt32\x12\x19\n" +
	"\bf_int32s\x18\x04 \x03(\x05R\afInt32s\x121\n" +
	"\x06f_enum\x18\x05 \x01(\x0e2\x1a.grpcbin.DummyMessage.EnumR\x05fEnum\x123\n" +
	"\af_enums\x18\x06 \x03(\x0e2\x1a.grpcbin.DummyMessage.EnumR\x06fEnums\x12.\n" +
	"\x05f_sub\x18\a \x01(\v2\x19.grpcbin.DummyMessage.SubR\x04fSub\x120\n" +
	"\x06f_subs\x18\b \x03(\v2\x19.grpcbin.DummyMessage.SubR\x05fSubs\x12\x15\n" +
	"\x06f_bool\x18\t \x01(\bR\x05fBool\x12\x17\n" +
	"\af_bools\x18\n" +
	" \x03(\bR\x06fBools\x12\x17\n" +
	"\af_int64\x18\v \x01(\x03R\x06fInt64\x12\x19\n" +
	"\bf_int64s\x18\f \x03(\x03R\afInt64s\x12\x17\n" +
	"\af_bytes\x18\r \x01(\fR\x06fBytes\x12\x19\n" +
	"\bf_bytess\x18\x0e \x03(\fR\afBytess\x12\x17\n" +
	"\af_float\x18\x0f \x01(\x02R\x06fFloat\x12\x19\n" +
	"\bf_floats\x18\x10 \x03(\x02R\afFloats\x1a \n" +
	"\x03Sub\x12\x19\n" +
	"\bf_string\x18\x01 \x01(\tR\afString\"*\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06ENUM_0\x10\x00\x12\n" +
	"\n" +
	"\x06ENUM_1\x10\x01\x12\n" +
	"\n" +
	"\x06ENUM_2\x10\x02\"\xac\x01\n" +
	"\n" +
	"IndexReply\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12:\n" +
	"\tendpoints\x18\x02 \x03(\v2\x1c.grpcbin.IndexReply.EndpointR\tendpoints\x1a@\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2\xa8\x05\n" +
	"\aGRPCBin\x125\n" +
	"\x05Index\x12\x15.grpcbin.EmptyMessage\x1a\x13.grpcbin.IndexReply\"\x00\x127\n" +
	"\x05Empty\x12\x15.grpcbin.EmptyMessage\x1a\x15.grpcbin.EmptyMessage\"\x00\x12<\n" +
	"\n" +
	"DummyUnary\x12\x15.grpcbin.DummyMessage\x1a\x15.grpcbin.DummyMessage\"\x00\x12E\n" +
	"\x11DummyServerStream\x12\x15.grpcbin.DummyMessage\x1a\x15.grpcbin.DummyMessage\"\x000\x01\x12E\n" +
	"\x11DummyClientStream\x12\x15.grpcbin.DummyMessage\x1a\x15.grpcbin.DummyMessage\"\x00(\x01\x12T\n" +
	"\x1eDummyBidirectionalStreamStream\x12\x15.grpcbin.DummyMessage\x1a\x15.grpcbin.DummyMessage\"\x00(\x010\x01\x12G\n" +
	"\rSpecificError\x12\x1d.grpcbin.SpecificErrorRequest\x1a\x15.grpcbin.EmptyMessage\"\x00\x12=\n" +
	"\vRandomError\x12\x15.grpcbin.EmptyMessage\x1a\x15.grpcbin.EmptyMessage\"\x00\x12@\n" +
	"\fHeadersUnary\x12\x15.grpcbin.EmptyMessage\x1a\x17.grpcbin.HeadersMessage\"\x00\x12A\n" +
	"\x0fNoResponseUnary\x12\x15.grpcbin.EmptyMessage\x1a\x15.grpcbin.EmptyMessage\"\x00B\x0fZ\rproto/grpcbinb\x06proto3"

var (
	file_proto_grpcbin_grpcbin_proto_rawDescOnce sync.Once
	file_proto_grpcbin_grpcbin_proto_rawDescData []byte
)

func file_proto_grpcbin_grpcbin_proto_rawDescGZIP() []byte {
	file_proto_grpcbin_grpcbin_proto_rawDescOnce.Do(func() {
		file_proto_grpcbin_grpcbin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpcbin_grpcbin_proto_rawDesc), len(file_proto_grpcbin_grpcbin_proto_rawDesc)))
	})
	return file_proto_grpcbin_grpcbin_proto_rawDescData
}

var file_proto_grpcbin_grpcbin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_grpcbin_grpcbin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_grpcbin_grpcbin_proto_goTypes = []any{
	(DummyMessage_Enum)(0),        // 0: grpcbin.DummyMessage.Enum
	(*HeadersMessage)(nil),        // 1: grpcbin.HeadersMessage
	(*SpecificErrorRequest)(nil),  // 2: grpcbin.SpecificErrorRequest
	(*EmptyMessage)(nil),          // 3: grpcbin.EmptyMessage
	(*DummyMessage)(nil),          // 4: grpcbin.DummyMessage
	(*IndexReply)(nil),            // 5: grpcbin.IndexReply
	(*HeadersMessage_Values)(nil), // 6: grpcbin.HeadersMessage.Values
	nil,                           // 7: grpcbin.HeadersMessage.MetadataEntry
	(*DummyMessage_Sub)(nil),      // 8: grpcbin.DummyMessage.Sub
	(*IndexReply_Endpoint)(nil),   // 9: grpcbin.IndexReply.Endpoint
}
var file_proto_grpcbin_grpcbin_proto_depIdxs = []int32{
	7,  // 0: grpcbin.HeadersMessage.Metadata:type_name -> grpcbin.HeadersMessage.MetadataEntry
	0,  // 1: grpcbin.DummyMessage.f_enum:type_name -> grpcbin.DummyMessage.Enum
	0,  // 2: grpcbin.DummyMessage.f_enums:type_name -> grpcbin.DummyMessage.Enum
	8,  // 3: grpcbin.DummyMessage.f_sub:type_name -> grpcbin.DummyMessage.Sub
	8,  // 4: grpcbin.DummyMessage.f_subs:type_name -> grpcbin.DummyMessage.Sub
	9,  // 5: grpcbin.IndexReply.endpoints:type_name -> grpcbin.IndexReply.Endpoint
	6,  // 6: grpcbin.HeadersMessage.MetadataEntry.value:type_name -> grpcbin.HeadersMessage.Values
	3,  // 7: grpcbin.GRPCBin.Index:input_type -> grpcbin.EmptyMessage
	3,  // 8: grpcbin.GRPCBin.Empty:input_type -> grpcbin.EmptyMessage
	4,  // 9: grpcbin.GRPCBin.DummyUnary:input_type -> grpcbin.DummyMessage
	4,  // 10: grpcbin.GRPCBin.DummyServerStream:input_type -> grpcbin.DummyMessage
	4,  // 11: grpcbin.GRPCBin.DummyClientStream:input_type -> grpcbin.DummyMessage
	4,  // 12: grpcbin.GRPCBin.DummyBidirectionalStreamStream:input_type -> grpcbin.DummyMessage
	2,  // 13: grpcbin.GRPCBin.SpecificError:input_type -> grpcbin.SpecificErrorRequest
	3,  // 14: grpcbin.GRPCBin.RandomError:input_type -> grpcbin.EmptyMessage
	3,  // 15: grpcbin.GRPCBin.HeadersUnary:input_type -> grpcbin.EmptyMessage
	3,  // 16: grpcbin.GRPCBin.NoResponseUnary:input_type -> grpcbin.EmptyMessage
	5,  // 17: grpcbin.GRPCBin.Index:output_type -> grpcbin.IndexReply
	3,  // 18: grpcbin.GRPCBin.Empty:output_type -> grpcbin.EmptyMessage
	4,  // 19: grpcbin.GRPCBin.DummyUnary:output_type -> grpcbin.DummyMessage
	4,  // 20: grpcbin.GRPCBin.DummyServerStream:output_type -> grpcbin.DummyMessage
	4,  // 21: grpcbin.GRPCBin.DummyClientStream:output_type -> grpcbin.DummyMessage
	4,  // 22: grpcbin.GRPCBin.DummyBidirectionalStreamStream:output_type -> grpcbin.DummyMessage
	3,  // 23: grpcbin.GRPCBin.SpecificError:output_type -> grpcbin.EmptyMessage
	3,  // 24: grpcbin.GRPCBin.RandomError:output_type -> grpcbin.EmptyMessage
	1,  // 25: grpcbin.GRPCBin.HeadersUnary:output_type -> grpcbin.HeadersMessage
	3,  // 26: grpcbin.GRPCBin.NoResponseUnary:output_type -> grpcbin.EmptyMessage
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_grpcbin_grpcbin_proto_init() }
func file_proto_grpcbin_grpcbin_proto_init() {
	if File_proto_grpcbin_grpcbin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpcbin_grpcbin_proto_rawDesc), len(file_proto_grpcbin_grpcbin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcbin_grpcbin_proto_goTypes,
		DependencyIndexes: file_proto_grpcbin_grpcbin_proto_depIdxs,
		EnumInfos:         file_proto_grpcbin_grpcbin_proto_enumTypes,
		MessageInfos:      file_proto_grpcbin_grpcbin_proto_msgTypes,
	}.Build()
	File_proto_grpcbin_grpcbin_proto = out.File
	file_proto_grpcbin_grpcbin_proto_goTypes = nil
	file_proto_grpcbin_grpcbin_proto_depIdxs = nil
}
